### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by trash-anger** [danielbayley/atom-gitkraken#4]
Hi, I'm looking for a new dev workflow and and try to use atom with GitKraken (so with your package). When I try to open a project, an error appear.

What did I miss ?
1. Just open atom with atom-gitkraken package installed
2. Packages -> Open project in GitKraken

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [gitkraken](https://github.com/danielbayley/atom-gitkraken) package, v0.4.1
### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/admin/.atom/packages/gitkraken/index.coffee:29

TypeError: Cannot read property 'path' of undefined
    at Object.module.exports.open (/Users/admin/.atom/packages/gitkraken/index.coffee:29:9)
    at atom-workspace.subs.add.atom.commands.add.gitkraken:release (/Users/admin/.atom/packages/gitkraken/index.coffee:22:29)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -1:41.5.0 command-palette:toggle (atom-pane.pane.active)
  2x -1:34.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:29.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:28.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.3.0 gitkraken:release (atom-pane.pane.active)
     -1:24.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  4x -1:21.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:17.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 gitkraken:release (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
gitkraken, v0.4.1
gitlab, v0.1.3-7

# Dev
No dev packages
```

**Comment by danielbayley** [comment]
@trash-anger Did you have a project root folder set?
What happens if you run `atom.project.getDirectories()[0]` in the dev tools console?

**Comment by trash-anger** [comment]
Apparently I tried without a projet root folder set at the beginning, but after filling it, the issue occurs again the same way :

> Directory {symlink: false, emitter: Emitter, subscriptionCounts: Object, eventHandlersByEventName: Object, path: "/Users/admin/Documents/git"…}

**Comment by trash-anger** [comment]
Two weird things : 

> $ which node 

return nothing 
> $ which git

return : /usr/local/bin/git

what about you ?

**Comment by danielbayley** [comment]
? Where are you running these from?

From **Terminal** I get:
~~~ sh
$ which node
/usr/local/bin/node # via brew install node

$ which git
/usr/local/bin/git # via brew install git
~~~

**Comment by trash-anger** [comment]
Yes

**Comment by thegiantbeast** [comment]
This also happens to me when I right-click the on the branch (bottom right corner of Atom).
